apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-memos-httproute
  namespace: oauth2-proxy-memos
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: memos
  to:
    - group: ""
      kind: Service
      name: oauth2-proxy-memos
