
driver:
  name: nfs.csi.k8s.io
  replicas: 1

storageClass:
  create: true
  name: nfs-csi
  parameters:
    server: 10.0.0.5
    share: /mnt/General/longhorn/
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  mountOptions:
    - nfsvers=4.1

csiDriver:
  name: nfs.csi.k8s.io
  attachRequired: false
  fsGroupPolicy: File

kubeletDir: /var/lib/kubelet
