apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
helmCharts:
  - name: metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server
    version: 3.14.0 # renovate: github-releases=kubernetes-sigs/metrics-server
    releaseName: metrics-server
    namespace: metrics-server
    valuesFile: values.yaml
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-10"