apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: headscale
  namespace: headscale
spec:
  parentRefs:
    - name: gateway-headscale
      namespace: headscale
  hostnames:
    - "headscale.jvos.dev"
  rules:
    - backendRefs:
        - name: headscale
          namespace: headscale
          port: 443
