apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: degoog

resources:
  - namespace.yaml
  - storage.yaml
  - postgres-cluster.yaml
  - valkey.yaml
  - degoog.yaml
  - httproute.yaml
