apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale-router

resources:
  - namespace.yaml
  - pvc.yaml
  - secrets.yaml
  - deployment.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "8" # After headscale (7) - needs it reachable to register
